apiVersion: v1
kind: Service
metadata:
  name: carta-shared
  labels:
    run: carta-shared
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30003
    protocol: TCP
  selector:
    run: carta-shared