apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: carta-core
  name: carta-core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: carta-core
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: carta-core
    spec:
      containers:
        - image: carta-core:latest
          name: carta-core
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /opt/images
              name: carta-core-claim0
      restartPolicy: Always
      volumes:
        - name: carta-core-claim0
          persistentVolumeClaim:
            claimName: carta-core-claim0
status: {}
