apiVersion: v1
kind: Service
metadata:
  name: od
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: od
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: od
spec:
  selector:
    matchLabels:
      app: od
  replicas: 1
  template:
    metadata:
      labels:
        app: od
    spec:
      containers:
      - name: od
        image: od:v1
        ports:
        - containerPort: 5678
