apiVersion: v1
kind: Service
metadata:
  name: carta-dev
  labels:
    run: carta-dev
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002
    protocol: TCP
  selector:
    run: carta-dev