apiVersion: v1
kind: Service
metadata:
  name: carta-shared-fs
  labels:
    run: carta-shared-fs
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30004
    protocol: TCP
  selector:
    run: carta-shared-fs