apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: carta-mongodb
  name: carta-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: carta-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: carta-mongodb
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: mongo
          name: carta-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: carta-mongodb-claim0
      restartPolicy: Always
      volumes:
        - name: carta-mongodb-claim0
          persistentVolumeClaim:
            claimName: carta-mongodb-claim0
status: {}
